/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafit.visual;

import com.mycompany.javafit.*;
import java.util.ArrayList;

/**
 * Clase que representa la ventana principal de gestión para los socios.
 * Permite visualizar el perfil, consultar/reservar actividades y gestionar reservas.
 *
 * @author Usuario
 */

public class VentanaGestionSocio extends javax.swing.JFrame {
    /**
     * Creates new form VentanaSocio.
     * Inicializa los componentes, carga los datos del perfil del socio
     * y rellena las tablas de actividades y reservas.
     */
    public VentanaGestionSocio() {
        initComponents();
        cargarDatosPerfil();
        cargarTablaActividades("Todos", "", "Todos");
        cargarTablaMisReservas();
    }
    /**
     * Carga en la tabla correspondiente las reservas asociadas al socio actual.
     * Filtra la lista global de reservas del gimnasio para mostrar únicamente
     * las del usuario logeado.
     */
    private void cargarTablaMisReservas() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();

        modelo.setRowCount(0);

        Socio socioActual = (Socio) Gimnasio.getInstancia().getUsuarioLogeado();

        if (socioActual != null) {

            ArrayList<Reserva> todasLasReservas = Gimnasio.getInstancia().getReservas();

            if (todasLasReservas != null) {
                for (Reserva res : todasLasReservas) {

                    if (res.getCliente() != null && res.getCliente().getCorreo().equals(socioActual.getCorreo())) {

                        Object[] fila = new Object[4];

                        fila[0] = res.getFechaReserva();          
                        fila[1] = res.getActividad().getTitulo();   
                        fila[2] = res.getHorario().getDia();
                        fila[3] = res.getHorario().getTurno();
                        

                        modelo.addRow(fila);
                    }
                }
            }
        }
    }
    
    private void cargarTablaActividades(String tipoFiltro, String monitorFiltro, String diaFiltro) {

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaActividades.getModel();
        modelo.setRowCount(0);

        ArrayList<Actividad> listaActividades = Gimnasio.getInstancia().getActividades();

        if (listaActividades != null) {
            for (Actividad act : listaActividades) {

                if (!tipoFiltro.equals("Todos") && !act.getTipo().equalsIgnoreCase(tipoFiltro)) {
                    continue;
                }

                if (!monitorFiltro.isEmpty() && !act.getMonitor().toLowerCase().contains(monitorFiltro.toLowerCase())) {
                    continue;
                }

                if (act.getHorarios() != null) {
                    for (Horario h : act.getHorarios()) {

                        if (diaFiltro.equals("Todos") || diaFiltro.isEmpty() || h.getDia().equalsIgnoreCase(diaFiltro)) {
                            
                            Object[] fila = new Object[5]; 
                            fila[0] = act.getTitulo(); 
                            fila[1] = act.getTipo();    
                            fila[2] = act.getMonitor();
                            fila[3] = h.getDia();       
                            fila[4] = h.getTurno();    

                            modelo.addRow(fila);
                        }
                    }
                }
            }
        }
    }
    /**
     * Carga los datos del socio logeado en los campos de texto correspondientes
     * a la pestaña de "Mi Perfil".
     */
    private void cargarDatosPerfil() {
        Socio socioActual = (Socio) Gimnasio.getInstancia().getUsuarioLogeado();
        
        if (socioActual != null) {
            campoNombre.setText(socioActual.getNombre());
            campoCorreo.setText(socioActual.getCorreo());
            campoTelefono.setText(socioActual.getTelefono());
            campoDireccion.setText(socioActual.getDireccion());
            campoTarjeta.setText(socioActual.getTarjetaCredito());
            campoClave.setText(socioActual.getClave());
            
            if(socioActual.isSocioVIP() == true){
                jCheckBoxSocioVIP.setSelected(true);
            }            
            else {
                jCheckBoxSocioVIP.setSelected(false);

            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollBar1 = new javax.swing.JScrollBar();
        campoMonitor1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        BusquedaYReserva = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JComboBox<>();
        jLabelDia = new javax.swing.JLabel();
        campoMonitor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActividades = new javax.swing.JTable();
        botonReservar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoDia = new javax.swing.JComboBox<>();
        MisReservas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cancelarReserva = new javax.swing.JButton();
        jComboBoxNotas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonValorar = new javax.swing.JButton();
        jTextFieldComentario = new javax.swing.JTextField();
        MiPerfil = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTarjeta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoClave = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        botonGuardarCambios = new javax.swing.JButton();
        jCheckBoxSocioVIP = new javax.swing.JCheckBox();

        jPasswordField1.setText("jPasswordField1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("JavaFit");

        jLabel2.setText("Tipo:");

        campoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Musculación", "Cardio", "Natación", "Todos" }));

        jLabelDia.setText("Dia:");

        jButton1.setText("Buscar ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tablaActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Tipo", "Monitor", "Dia", "Turno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActividades.getTableHeader().setReorderingAllowed(false);
        tablaActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaActividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaActividades);
        if (tablaActividades.getColumnModel().getColumnCount() > 0) {
            tablaActividades.getColumnModel().getColumn(2).setResizable(false);
        }

        botonReservar.setText("Reservar Clase Seleccionada");
        botonReservar.addActionListener(this::botonReservarActionPerformed);

        jLabel4.setText("Monitor:");

        campoDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo", "Todos" }));

        javax.swing.GroupLayout BusquedaYReservaLayout = new javax.swing.GroupLayout(BusquedaYReserva);
        BusquedaYReserva.setLayout(BusquedaYReservaLayout);
        BusquedaYReservaLayout.setHorizontalGroup(
            BusquedaYReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusquedaYReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BusquedaYReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(BusquedaYReservaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BusquedaYReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BusquedaYReservaLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(38, 38, 38)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(BusquedaYReservaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMonitor)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDia)
                                .addGap(12, 12, 12)
                                .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusquedaYReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReservar)
                .addGap(161, 161, 161))
        );
        BusquedaYReservaLayout.setVerticalGroup(
            BusquedaYReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusquedaYReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BusquedaYReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDia)
                    .addComponent(campoMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BusquedaYReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(botonReservar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Búsqueda y Reserva", BusquedaYReserva);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha de la reserva", "Actividad", "Dia", "Turno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        cancelarReserva.setText("Cancelar Reserva");
        cancelarReserva.addActionListener(this::cancelarReservaActionPerformed);

        jComboBoxNotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxNotas.addActionListener(this::jComboBoxNotasActionPerformed);

        jLabel3.setText("Valorar actividad seleccionada:");

        jButtonValorar.setText("Enviar valoración");
        jButtonValorar.addActionListener(this::jButtonValorarActionPerformed);

        javax.swing.GroupLayout MisReservasLayout = new javax.swing.GroupLayout(MisReservas);
        MisReservas.setLayout(MisReservasLayout);
        MisReservasLayout.setHorizontalGroup(
            MisReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MisReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MisReservasLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(cancelarReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MisReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MisReservasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldComentario))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MisReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonValorar)
                .addGap(105, 105, 105))
        );
        MisReservasLayout.setVerticalGroup(
            MisReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MisReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MisReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarReserva)
                    .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonValorar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Reservas", MisReservas);

        jLabel5.setText("Nombre:");

        jLabel6.setText("Correo:");

        jLabel7.setText("Teléfono:");

        jLabel8.setText("Dirección:");

        jLabel9.setText("Tarjeta de crédito:");

        jLabel10.setText("Contraseña:");

        botonGuardarCambios.setText("Guardar Cambios");
        botonGuardarCambios.addActionListener(this::botonGuardarCambiosActionPerformed);

        jCheckBoxSocioVIP.setText("Socio VIP");

        javax.swing.GroupLayout MiPerfilLayout = new javax.swing.GroupLayout(MiPerfil);
        MiPerfil.setLayout(MiPerfilLayout);
        MiPerfilLayout.setHorizontalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiPerfilLayout.createSequentialGroup()
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCorreo))
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNombre))
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTelefono))
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDireccion))
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiPerfilLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MiPerfilLayout.createSequentialGroup()
                                        .addGap(196, 196, 196)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(MiPerfilLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoClave))))))
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxSocioVIP))
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(botonGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        MiPerfilLayout.setVerticalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiPerfilLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxSocioVIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(botonGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mi Perfil", MiPerfil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Maneja el evento de clic en el botón de búsqueda de actividades.
     * Aplica los filtros de tipo, monitor y día seleccionados en la interfaz.
     *
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String tipoElegido = campoTipo.getSelectedItem().toString(); 
        String monitorEscrito = campoMonitor.getText().trim();
        String diaElegido = campoDia.getSelectedItem().toString(); 

        cargarTablaActividades(tipoElegido, monitorEscrito, diaElegido);
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Maneja el evento de clic en el botón para limpiar los filtros de actividades.
     * Restablece los campos de búsqueda y recarga todas las actividades.
     *
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        campoTipo.setSelectedIndex(4);
        campoMonitor.setText("");
        campoDia.setSelectedIndex(7);
        
        cargarTablaActividades("Todos", "","Todos");
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Maneja el evento de clic en el botón para cancelar una reserva.
     * Solicita confirmación al usuario y elimina la reserva seleccionada en la tabla.
     *
     * @param evt Evento de acción disparado por el botón.
     */
    private void cancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarReservaActionPerformed

            int filaSeleccionada = jTable2.getSelectedRow();

            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona la reserva que deseas cancelar.");
                return;
            }

            String tituloActividad = jTable2.getValueAt(filaSeleccionada, 1).toString().trim();
            String diaClase = jTable2.getValueAt(filaSeleccionada, 2).toString().trim();
            String turnoClase = jTable2.getValueAt(filaSeleccionada, 3).toString().trim();

            Socio socioActual = (Socio) Gimnasio.getInstancia().getUsuarioLogeado();

            if (socioActual != null) {
                ArrayList<Reserva> listaReservasSistema = Gimnasio.getInstancia().getReservas();
                Reserva reservaAEliminar = null;

                if (listaReservasSistema != null) {
                    for (Reserva res : listaReservasSistema) {
                        if (res.getCliente() != null && res.getCliente().getCorreo().equals(socioActual.getCorreo()) && res.getActividad() != null && res.getActividad().getTitulo().equalsIgnoreCase(tituloActividad) && res.getHorario() != null && res.getHorario().getDia().equalsIgnoreCase(diaClase) && res.getHorario().getTurno().equalsIgnoreCase(turnoClase)) {

                            reservaAEliminar = res;
                            break; 
                        }
                    }
                }

                if (reservaAEliminar != null) {
                    listaReservasSistema.remove(reservaAEliminar);
                    Gimnasio.getInstancia().guardarDatos();
                    javax.swing.JOptionPane.showMessageDialog(this, "La reserva se ha cancelado correctamente.");
                    cargarTablaMisReservas();
                }
            }
    }//GEN-LAST:event_cancelarReservaActionPerformed

   /**
     * Maneja el evento de clic en el botón para guardar cambios en el perfil.
     * Actualiza los datos del socio activo con la información introducida en los campos.
     *
     * @param evt Evento de acción disparado por el botón.
     */
    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed

        Socio socioActual = (Socio) Gimnasio.getInstancia().getUsuarioLogeado();

        if (socioActual != null) {

            socioActual.setNombre(campoNombre.getText().trim());
            socioActual.setTelefono(campoTelefono.getText().trim());
            socioActual.setDireccion(campoDireccion.getText().trim());
            socioActual.setTarjetaCredito(campoTarjeta.getText().trim());
            String nuevaClave = new String(campoClave.getPassword());
            socioActual.setClave(nuevaClave);
            socioActual.setSocioVIP(jCheckBoxSocioVIP.isSelected());
            
            Gimnasio.getInstancia().guardarDatos();
            javax.swing.JOptionPane.showMessageDialog(this, "Tus datos se han actualizado correctamente.");
        } 
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se ha podido identificar al usuario.");
        }
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed
    /**
     * Maneja el evento de clic en el botón para reservar una actividad.
     * Verifica la selección, comprueba si ya existe la reserva, y la efectúa
     * generando un recibo si es exitosa.
     *
     * @param evt Evento de acción disparado por el botón.
     */
    private void botonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActionPerformed
                                             
        int filaSeleccionada = tablaActividades.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Haz clic en una actividad de la tabla.");
            return; 
        }

        String tituloClase = tablaActividades.getValueAt(filaSeleccionada, 0).toString();
        String diaElegido = tablaActividades.getValueAt(filaSeleccionada, 3).toString();
        String turnoElegido = tablaActividades.getValueAt(filaSeleccionada, 4).toString();
        
        Actividad actividadElegida = Gimnasio.getInstancia().getActividades().stream()
                .filter(act -> act.getTitulo().equals(tituloClase))
                .findFirst()
                .orElse(null);

        Socio socioActual = (Socio) Gimnasio.getInstancia().getUsuarioLogeado();

        if (actividadElegida != null && socioActual != null) {

        Horario horarioElegido = null;

        if (actividadElegida.getHorarios() != null) {
            horarioElegido = actividadElegida.getHorarios().stream()
                    .filter(h -> h.getDia().equalsIgnoreCase(diaElegido) && h.getTurno().equalsIgnoreCase(turnoElegido))
                    .findFirst()
                    .orElse(null);
        }

        if (horarioElegido == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al recuperar el horario interno de la actividad.");
            return;
        }

        boolean existeReserva= false;
        ArrayList<Reserva> listaReservasSistema = Gimnasio.getInstancia().getReservas();

        if (listaReservasSistema != null) {
            for (Reserva res : listaReservasSistema) {
                if (res.getCliente() != null && res.getCliente().getCorreo().equals(socioActual.getCorreo()) &&
                    res.getActividad() != null && res.getActividad().getTitulo().equalsIgnoreCase(actividadElegida.getTitulo()) &&
                    res.getHorario() != null && res.getHorario().getDia().equalsIgnoreCase(horarioElegido.getDia()) &&
                    res.getHorario().getTurno().equalsIgnoreCase(horarioElegido.getTurno())) {

                    existeReserva = true;
                    break; 
                }
            }
        }

        if (existeReserva) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Ya estás inscrito en " + tituloClase + " el " + diaElegido + " en el turno de " + turnoElegido.toLowerCase(), "Reserva ya existente", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }

        boolean exito = Gimnasio.getInstancia().reservar(actividadElegida, socioActual, horarioElegido);

        if (exito) {
            Gimnasio.getInstancia().guardarDatos();

            try {
                ArrayList<Reserva> listaRes = Gimnasio.getInstancia().getReservas();
                if (listaRes != null && !listaRes.isEmpty()) {
                    Reserva ultimaReserva = listaRes.get(listaRes.size() - 1);
                    Gimnasio.getInstancia().generaFactura(ultimaReserva);
                }
            } catch (java.io.IOException e) {
                System.out.println("Error de escritura en disco al generar la factura: " + e.getMessage());
            }

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Reserva realizada.\nActividad: " + tituloClase + "\nHorario: " + diaElegido + " (" + turnoElegido + ")");
            
            cargarTablaMisReservas(); 
            
        } 
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "No quedan plazas disponibles. El aforo de la sala está completo.", "Sala llena", javax.swing.JOptionPane.ERROR_MESSAGE);
        }                                            
        } 
        else {
           javax.swing.JOptionPane.showMessageDialog(this, "Error de autenticación o actividad no encontrada.", "Error crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_botonReservarActionPerformed
    /**
     * Maneja el evento de clic con el ratón en la tabla de actividades.
     * Abre la ventana de detalles de la actividad seleccionada.
     *
     * @param evt Evento de ratón disparado por la tabla.
     */
    private void tablaActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaActividadesMouseClicked
        int fila = tablaActividades.getSelectedRow();

        if (fila >= 0) {

            String titulo = tablaActividades.getValueAt(fila, 0).toString();

            Actividad actSeleccionada = Gimnasio.getInstancia().getActividades().stream()
                    .filter(a -> a.getTitulo().equalsIgnoreCase(titulo))
                    .findFirst()
                    .orElse(null);

            if (actSeleccionada != null) {
                if (actSeleccionada instanceof ActividadEspecial) {
                    VentanaActividadEspecial ficha = new VentanaActividadEspecial((ActividadEspecial) actSeleccionada);
                    ficha.setVisible(true);
                    ficha.setLocationRelativeTo(null);
                    ficha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                } else {
                    VentanaActividad ficha = new javafit.visual.VentanaActividad(actSeleccionada);
                    ficha.setVisible(true);
                    ficha.setLocationRelativeTo(null);
                    ficha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                }
            }
        }
    }//GEN-LAST:event_tablaActividadesMouseClicked

   /**
     * Maneja el evento de clic con el ratón en la tabla de reservas.
     * Abre la ventana de detalles de la reserva seleccionada.
     *
     * @param evt Evento de ratón disparado por la tabla.
     */
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int filaSeleccionada = jTable2.getSelectedRow();

        if (filaSeleccionada >= 0) {
            String tituloActividad = jTable2.getValueAt(filaSeleccionada, 1).toString().trim();
            String diaClase = jTable2.getValueAt(filaSeleccionada, 2).toString().trim();
            String turnoClase = jTable2.getValueAt(filaSeleccionada, 3).toString().trim();

            Reserva reservaEncontrada = Gimnasio.getInstancia().getReservas().stream()
                    .filter(res -> res.getActividad() != null && res.getActividad().getTitulo().equalsIgnoreCase(tituloActividad)&& res.getHorario() != null && res.getHorario().getDia().equalsIgnoreCase(diaClase) && res.getHorario().getTurno().equalsIgnoreCase(turnoClase))
                    .findFirst()
                    .orElse(null);

            if (reservaEncontrada != null) {
                VentanaReserva vr = new VentanaReserva(reservaEncontrada);
                vr.setLocationRelativeTo(null); 
                vr.setVisible(true);
            }
        }


    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBoxNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNotasActionPerformed

    private void jButtonValorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValorarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTable2.getSelectedRow();

        if (filaSeleccionada >= 0){
            String tituloActividad = jTable2.getValueAt(filaSeleccionada, 1).toString().trim();

            Actividad actividadBuscada = Gimnasio.getInstancia().getActividades().stream()
                    .filter(act -> act.getTitulo().equalsIgnoreCase(tituloActividad))
                    .findFirst()
                    .orElse(null);

            if (actividadBuscada != null){
                int nota = (int) jComboBoxNotas.getSelectedItem();
                String comentario = jTextFieldComentario.getText().trim();

                Valoracion nuevaValoracion = new Valoracion(nota, comentario);

                actividadBuscada.registrarValoracion(nuevaValoracion);
                actividadBuscada.calcularNotaMedia();

                Gimnasio.getInstancia().guardarDatos();
            }
        }

    }//GEN-LAST:event_jButtonValorarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BusquedaYReserva;
    private javax.swing.JPanel MiPerfil;
    private javax.swing.JPanel MisReservas;
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JButton botonReservar;
    private javax.swing.JPasswordField campoClave;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JComboBox<String> campoDia;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoMonitor;
    private javax.swing.JTextField campoMonitor1;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTarjeta;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox<String> campoTipo;
    private javax.swing.JButton cancelarReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonValorar;
    private javax.swing.JCheckBox jCheckBoxSocioVIP;
    private javax.swing.JComboBox<String> jComboBoxNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldComentario;
    private javax.swing.JTable tablaActividades;
    // End of variables declaration//GEN-END:variables
}
