/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafit.visual;

/**
 *
 * @author Dani
 */
import com.mycompany.javafit.*;
import javax.swing.JList;

public class VentanaSocio extends javax.swing.JFrame implements javax.swing.event.ListSelectionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaSocio.class.getName());
    private Socio socio;
    /**
     * Creates new form VentanaSocio
     */
    
    @Override
    public void valueChanged(javax.swing.event.ListSelectionEvent e) {
        // Evitamos que el evento se dispare dos veces (al presionar y al soltar)
        if (!e.getValueIsAdjusting()) {

            // 1. Capturamos el nombre de la actividad que el usuario ha seleccionado
            String actividadSeleccionada = jListReservas.getSelectedValue();

            if (actividadSeleccionada != null && this.socio != null && this.socio.getReservas() != null) {

                // 2. Buscamos en el ArrayList del socio cuál es la Reserva que pertenece a esa actividad
                Reserva reservaEncontrada = null;
                for (Reserva r : this.socio.getReservas()) {
                    if (r.getActividad().getTitulo().equals(actividadSeleccionada)) {
                        reservaEncontrada = r;
                        break; // Ya la encontramos, paramos el bucle
                    }
                }
                // 3. Si la encontramos, abrimos su ventana pasándole la reserva real con todos sus datos
                if (reservaEncontrada != null) {
                    VentanaReserva vr = new VentanaReserva(reservaEncontrada);
                    vr.setVisible(true);
                }
            }
        }
    }
    
    public VentanaSocio(Socio socio) {
        initComponents();
        this.socio = socio;
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        if (this.socio != null) {
            // 1. Rellenamos los campos de texto del Socio
            jTextFieldNombre.setText(this.socio.getNombre());
            jTextFieldTelefono.setText(this.socio.getTelefono());
            jTextFieldDireccion.setText(this.socio.getDireccion());
            jTextFieldTarjetaCredito.setText(this.socio.getTarjetaCredito());
            
            // 2. Controlamos el estado del CheckBox VIP
            jCheckBoxSocioVIP.setSelected(this.socio.isSocioVIP());
            // Lo dejamos deshabilitado para que solo sea de lectura/visualización
            jCheckBoxSocioVIP.setEnabled(false); 
            
            // --- RELLENAR EL JLIST CON LOS NOMBRES DE LAS ACTIVIDADES ---
            if (this.socio.getReservas() != null) {

                // 1. Creamos un array de Strings del mismo tamaño que las reservas del socio
                int tamano = this.socio.getReservas().size();
                String[] nombres_actividades = new String[tamano];

                // 2. Llenamos el array guardando solo el nombre de la actividad de cada reserva
                for (int i = 0; i < tamano; i++) {
                    Reserva r = this.socio.getReservas().get(i);
                    nombres_actividades[i] = r.getActividad().getTitulo(); // O r.getNombreActividad(), según tu clase
                }

                // 3. Le pasamos el array de textos directamente al JList de NetBeans
                jListReservas.setListData(nombres_actividades);

                // 4. Configuramos para que solo se pueda seleccionar de uno en uno
                jListReservas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

                // 5. Le enlazamos el escuchador de eventos a esta ventana
                jListReservas.addListSelectionListener(this);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTarjetaCredito = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jCheckBoxSocioVIP = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListReservas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("SOCIO");

        jLabel3.setText("Teléfono");

        jLabel7.setText("Direccion");

        jLabel6.setText("Reservas");

        jTextFieldTarjetaCredito.setEditable(false);

        jTextFieldDireccion.setEditable(false);
        jTextFieldDireccion.addActionListener(this::jTextFieldDireccionActionPerformed);

        jLabel2.setText("Nombre");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.addActionListener(this::jTextFieldNombreActionPerformed);

        jTextFieldTelefono.setEditable(false);
        jTextFieldTelefono.addActionListener(this::jTextFieldTelefonoActionPerformed);

        jCheckBoxSocioVIP.setText("¿Es VIP?");
        jCheckBoxSocioVIP.addActionListener(this::jCheckBoxSocioVIPActionPerformed);

        jLabel8.setText("Tarjeta de crédito");

        jListReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDireccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombre))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTarjetaCredito))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jCheckBoxSocioVIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(jCheckBoxSocioVIP))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jCheckBoxSocioVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSocioVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSocioVIPActionPerformed

    private void jListReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListReservasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListReservasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxSocioVIP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTarjetaCredito;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
