/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafit.visual;

/**
 *
 * @author Usuario
 */

import com.mycompany.javafit.*;
import javax.swing.*;
import java.util.ArrayList;

public class VentanaAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName());

    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
        // Llamamos al método con "null, null" para que muestre a TODOS los socios al arrancar
        cargarTablaSocios(null, null);
    }
    private void cargarTablaSocios(String filtroCorreo, Boolean filtroVip) {
    // Obtenemos el "cerebro" de tu tabla (Asegúrate de que el nombre de tu JTable sea correcto, yo usaré tablaSocios)
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaSocios.getModel();
    
    // Vaciamos la tabla primero (para que no se dupliquen los datos si buscamos varias veces)
    modelo.setRowCount(0);
    
    // Le pedimos la lista a la clase de tu compañero
    // Su método buscarSocios acepta null si queremos ver a todo el mundo
    ArrayList<Socio> lista = Gimnasio.getInstancia().buscarSocios(filtroCorreo, filtroVip);
    
    // Recorremos la lista y metemos cada socio en la tabla
    for (com.mycompany.javafit.Socio s : lista) {
        
        // Creamos una "fila" con 6 huecos (uno por cada columna que pusiste en NetBeans)
        Object[] fila = new Object[6]; 
        
        // Usamos los getters de la clase Socio de tu compañero para rellenar los huecos
        fila[0] = s.getNombre();
        fila[1] = s.getCorreo();
        fila[2] = s.getTelefono();
        fila[3] = s.getDireccion();
        fila[4] = s.getTarjetaCredito(); // (En la vida real esto se oculta, ¡pero aquí lo mostramos!)
        fila[5] = s.isSocioVIP() ? "Sí" : "No"; // Si es true pone "Sí", si es false pone "No"
        
        // Añadimos la fila completa al modelo
        modelo.addRow(fila);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ConsultaDeActividades = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ConsultaDeSocios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoBusquedaCorreo = new javax.swing.JTextField();
        checkBoxVip = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        ConsultaDeReservas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        GestiónDeActividades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonGuardarActividad = new javax.swing.JButton();
        jButtonModificarActividad = new javax.swing.JButton();
        jButtonBorrarActividad = new javax.swing.JButton();
        campoTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        campoSala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoAforo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campoMonitor = new javax.swing.JTextField();
        checkBoxEspecial = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonImportarImagen = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Buscar por Tipo:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Musculación", "Cardio", "Natación", "Todos" }));

        jLabel8.setText("Monitor:");

        jButton4.setText("Buscar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Limpiar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Tipo", "Sala", "Aforo", "Horario", "Monitor", "Especial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout ConsultaDeActividadesLayout = new javax.swing.GroupLayout(ConsultaDeActividades);
        ConsultaDeActividades.setLayout(ConsultaDeActividadesLayout);
        ConsultaDeActividadesLayout.setHorizontalGroup(
            ConsultaDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        ConsultaDeActividadesLayout.setVerticalGroup(
            ConsultaDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Actividades", ConsultaDeActividades);

        jLabel9.setText("Buscar por Nombre:");

        jLabel10.setText("Correo electrónico:");

        checkBoxVip.setText("Socios VIP");
        checkBoxVip.addActionListener(this::checkBoxVipActionPerformed);

        jButton6.setText("Buscar");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Limpiar");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Teléfono", "Dirección", "Tarjeta", "¿Es VIP?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaSocios);

        javax.swing.GroupLayout ConsultaDeSociosLayout = new javax.swing.GroupLayout(ConsultaDeSocios);
        ConsultaDeSocios.setLayout(ConsultaDeSociosLayout);
        ConsultaDeSociosLayout.setHorizontalGroup(
            ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBusquedaCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxVip)
                .addGap(18, 18, 18))
            .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton6)
                .addGap(28, 28, 28)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        ConsultaDeSociosLayout.setVerticalGroup(
            ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoBusquedaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxVip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );

        jTabbedPane1.addTab("Consulta de Socios", ConsultaDeSocios);

        jLabel11.setText("Consultar desde la fecha:");

        jButton8.setText("Filtrar Reservas");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton9.setText("Ver todas");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Socio", "Actividad", "Horario", "Coste", "Recibo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout ConsultaDeReservasLayout = new javax.swing.GroupLayout(ConsultaDeReservas);
        ConsultaDeReservas.setLayout(ConsultaDeReservasLayout);
        ConsultaDeReservasLayout.setHorizontalGroup(
            ConsultaDeReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        ConsultaDeReservasLayout.setVerticalGroup(
            ConsultaDeReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Reservas", ConsultaDeReservas);

        jLabel1.setText("Título");

        jButtonGuardarActividad.setText("Guardar");
        jButtonGuardarActividad.addActionListener(this::jButtonGuardarActividadActionPerformed);

        jButtonModificarActividad.setText("Modificar");
        jButtonModificarActividad.addActionListener(this::jButtonModificarActividadActionPerformed);

        jButtonBorrarActividad.setText("Eliminar");
        jButtonBorrarActividad.addActionListener(this::jButtonBorrarActividadActionPerformed);

        campoTitulo.addActionListener(this::campoTituloActionPerformed);

        jLabel2.setText("Tipo de Actividad");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Musculación", "Cardio", "Natación" }));
        comboTipo.addActionListener(this::comboTipoActionPerformed);

        jLabel3.setText("Sala");

        jLabel4.setText("Aforo");

        jLabel5.setText("Horarios");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00 a 11:00", "11:00 a 12:00", "18:00 a 19:00", "19:00 a 20:00", "20:00 a 21:00" }));

        jLabel6.setText("Monitor");

        checkBoxEspecial.setText("¿Es actividad especial?");
        checkBoxEspecial.addActionListener(this::checkBoxEspecialActionPerformed);

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        jLabel13.setText("Precio");

        jLabel14.setText("Descripción:");

        jButtonImportarImagen.setText("Importar imágen");
        jButtonImportarImagen.addActionListener(this::jButtonImportarImagenActionPerformed);

        javax.swing.GroupLayout GestiónDeActividadesLayout = new javax.swing.GroupLayout(GestiónDeActividades);
        GestiónDeActividades.setLayout(GestiónDeActividadesLayout);
        GestiónDeActividadesLayout.setHorizontalGroup(
            GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jButtonGuardarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarActividad)
                        .addGap(101, 101, 101)
                        .addComponent(jButtonBorrarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(checkBoxEspecial)
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestiónDeActividadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonImportarImagen)
                .addGap(189, 189, 189))
        );
        GestiónDeActividadesLayout.setVerticalGroup(
            GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestiónDeActividadesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImportarImagen)
                .addGap(9, 9, 9)
                .addComponent(checkBoxEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarActividad)
                    .addComponent(jButtonModificarActividad)
                    .addComponent(jButtonBorrarActividad))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Gestión de Actividades", GestiónDeActividades);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("JavaFit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActividadActionPerformed
        // TODO add your handling code here:
        String titulo = campoTitulo.getText().trim();
        
        if (titulo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo 'Título' no puede estar vacío.","Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        // Buscamos la actividad original en el sistema utilizando la lista del Gimnasio
        ArrayList<Actividad> listaActividades = 
                com.mycompany.javafit.Gimnasio.getInstancia().getActividades();
        
        // Localizamos la actividad por su título (ignorando mayúsculas/minúsculas)
        Actividad act = listaActividades.stream()
                .filter(a -> a.getTitulo().equalsIgnoreCase(titulo))
                .findFirst()
                .orElse(null);

        // Si no existe, avisamos al usuario y paramos
        if (act == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "No se ha encontrado ninguna actividad con el título '" + titulo + "'.", "Actividad no encontrada", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si existe, recogemos el resto de nuevos datos de la interfaz para aplicar el cambio
        String nuevoTipo = comboTipo.getSelectedItem().toString();
        String nuevoMonitor = campoMonitor.getText().trim();
        String nombreSala = campoSala.getText().trim();

        if (nuevoMonitor.isEmpty() || nombreSala.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monitor y la sala no pueden quedar vacíos.");
            return;
        }

        try {
            // Validamos que el aforo sea un número correcto
            int nuevoAforo = Integer.parseInt(campoAforo.getText().trim());
            com.mycompany.javafit.Sala nuevaSala = new com.mycompany.javafit.Sala(nombreSala, nuevoAforo);

            // Variables para el caso de que sea una Actividad Especial
            double nuevoPrecio = 0;
            String nuevaDescripcion = "";

            if (checkBoxEspecial.isSelected()) {
                nuevoPrecio = Double.parseDouble(campoPrecio.getText().trim());
                nuevaDescripcion = campoDescripcion.getText().trim();
            }

            // Llamamos al método 'modificarActividad'
            boolean exito = com.mycompany.javafit.Gimnasio.getInstancia().modificarActividad(
                    act, titulo, nuevoTipo, nuevaSala, nuevoMonitor, 
                    this.imagenActividad, nuevoPrecio, nuevaDescripcion
            );

            // Informamos del resultado y limpiamos la pantalla
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Actividad '" + titulo + "' modificada con éxito");
                
                // Limpiamos los campos del formulario para dejarlo listo
                campoTitulo.setText("");
                campoMonitor.setText("");
                campoSala.setText("");
                campoAforo.setText("");
                campoPrecio.setText("");
                campoDescripcion.setText("");
                checkBoxEspecial.setSelected(false);
                this.imagenActividad = null;
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al intentar modificar.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error de formato: 'Aforo' y 'Precio' deben ser números.", 
                    "Error de datos", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActividadActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void checkBoxEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxEspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxEspecialActionPerformed

    private void jButtonGuardarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActividadActionPerformed
        // TODO add your handling code here:
        // Recogemos los datos de texto
        String titulo = campoTitulo.getText().trim();
        String tipo = comboTipo.getSelectedItem().toString(); 
        String monitor = campoMonitor.getText().trim();
        String nombreSala = campoSala.getText().trim();

    // Comprobación de que no falten datos clave
    if (titulo.isEmpty() || monitor.isEmpty() || nombreSala.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El título, monitor y sala son obligatorios.");
        return;
    }


    try {
        // Sacamos el número del aforo
        int aforo = Integer.parseInt(campoAforo.getText().trim());

        // Creamos la sala 
        Sala sala = new com.mycompany.javafit.Sala(nombreSala, aforo);

        boolean exito = false;

        // Comprobamos si es Especial o Normal
        if (checkBoxEspecial.isSelected()) { // Asegúrate de que tu checkbox se llame así
            double precio = Double.parseDouble(campoPrecio.getText().trim());
            String descripcion = campoDescripcion.getText().trim();

            exito = Gimnasio.getInstancia().crearActividad(
                    titulo, tipo, sala, monitor, this.imagenActividad, precio, descripcion);
        } else {
            exito = Gimnasio.getInstancia().crearActividad(
                    titulo, tipo, sala, monitor, this.imagenActividad);
        }

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Actividad '" + titulo + "' creada con éxito");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ya existe una actividad con ese título.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Deben introducirse números en 'Aforo' y 'Precio'");
    }
    }//GEN-LAST:event_jButtonGuardarActividadActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void checkBoxVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxVipActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            String correo = campoBusquedaCorreo.getText().trim();
            if (correo.isEmpty()) 
                correo = null; // Si está vacío, mandamos null

            // Comprobamos si marcó la casilla de VIP
            Boolean esVip = checkBoxVip.isSelected();
            if (!esVip) 
                esVip = null; // Si no la marcó, mandamos null para que no filtre por VIP

            // Recargamos la tabla con esos filtros
            cargarTablaSocios(correo, esVip);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonImportarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarImagenActionPerformed
        // TODO add your handling code here:
        
    javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
    
    javax.swing.filechooser.FileNameExtensionFilter filtro = 
            new javax.swing.filechooser.FileNameExtensionFilter("Imágenes (JPG, PNG)", "jpg", "jpeg", "png");
    selector.setFileFilter(filtro);
    
    int resultado = selector.showOpenDialog(this);
    
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivoImagen = selector.getSelectedFile();
        
        this.imagenActividad = new ImageIcon(archivoImagen.getAbsolutePath());
        
        }
    }//GEN-LAST:event_jButtonImportarImagenActionPerformed

    private void jButtonBorrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActividadActionPerformed
        // TODO add your handling code here:
            String titulo= campoTitulo.getText().trim();
            
            if (titulo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo 'Título' no puede estar vacío.","Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
            boolean eliminado= Gimnasio.getInstancia().borrarActividad(titulo);
            
            if (eliminado==true){
                javax.swing.JOptionPane.showMessageDialog(this, "Actividad eliminada correctamente.");
                
                campoTitulo.setText("");
                campoMonitor.setText("");
                campoSala.setText("");
                campoAforo.setText("");
                campoPrecio.setText("");
                campoDescripcion.setText("");
                this.imagenActividad = null;
            }
            else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna actividad con ese título.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_jButtonBorrarActividadActionPerformed

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConsultaDeActividades;
    private javax.swing.JPanel ConsultaDeReservas;
    private javax.swing.JPanel ConsultaDeSocios;
    private javax.swing.JPanel GestiónDeActividades;
    private javax.swing.JTextField campoAforo;
    private javax.swing.JTextField campoBusquedaCorreo;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoMonitor;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoSala;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JCheckBox checkBoxEspecial;
    private javax.swing.JCheckBox checkBoxVip;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBorrarActividad;
    private javax.swing.JButton jButtonGuardarActividad;
    private javax.swing.JButton jButtonImportarImagen;
    private javax.swing.JButton jButtonModificarActividad;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tablaSocios;
    // End of variables declaration//GEN-END:variables
    private javax.swing.ImageIcon imagenActividad = null;
}

