/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafit.visual;

/**
 * Clase que representa la ventana de gestión principal para el administrador.
 * Permite la consulta y gestión de actividades, socios y reservas.
 *
 * @author Usuario
 */

import com.mycompany.javafit.*;
import javax.swing.*;
import java.util.ArrayList;
import java.time.LocalDate;

public class VentanaGestionAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaGestionAdministrador.class.getName());

    /**
     * Creates new form VentanaAdministrador.
     * Inicializa los componentes de la interfaz y carga los datos iniciales
     * en las tablas de actividades, socios y reservas.
     */
    public VentanaGestionAdministrador() {
        initComponents();
        // Se cargan todas las tablas completas al principio
        cargarTablaActividades(null, null, null);
        cargarTablaSocios(null, null);
        cargarTablaReservas(null,null);
    }
     /**
     * Carga y filtra los datos de las actividades en la tabla correspondiente.
     * 
     * @param filtroTipo Tipo de actividad por el cual filtrar (o null para mostrar todos).
     * @param filtroMonitor Nombre del monitor por el cual filtrar (o null para no filtrar).
     * @param filtroDia Día específico para filtrar las actividades (o null para no filtrar).
     */
    private void cargarTablaActividades(String filtroTipo, String filtroMonitor, String filtroDia) {
        
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTableActividades.getModel(); // Se crea un modelo de tabla a partir de la tabla original
        modeloTabla.setRowCount(0); // Se vacía la tabla


        // Se realiza la búsqueda por filtros
        ArrayList<Actividad> lista = Gimnasio.getInstancia().buscarActividades(filtroTipo, filtroMonitor, filtroDia);

        for (Actividad act : lista) {

            // Se crea una fila con sus respectivas columnas en la fila
            Object[] fila = new Object[3]; 

            fila[0] = act.getTitulo();
            fila[1] = act.getTipo();
            fila[2] = act.getMonitor();

            modeloTabla.addRow(fila);
        }
    }
    /**
     * Carga y filtra los datos de los socios en la tabla correspondiente.
     * 
     * @param filtroCorreo Correo electrónico del socio para filtrar la búsqueda (o null).
     * @param filtroVip Valor booleano para filtrar solo socios VIP (o null para no aplicar este filtro).
     */ 
    private void cargarTablaSocios(String filtroCorreo, Boolean filtroVip) {
        
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTableSocios.getModel();
        modeloTabla.setRowCount(0);

        ArrayList<Socio> lista = Gimnasio.getInstancia().buscarSocios(filtroCorreo, filtroVip);

        for (Socio s : lista) {

            Object[] fila = new Object[3]; 

            fila[0] = s.getNombre();
            fila[1] = s.getCorreo();
            fila[2] = s.isSocioVIP() ? "Sí" : "No";

                modeloTabla.addRow(fila);
        }
    }
    /**
     * Carga y filtra las reservas en la tabla correspondiente.
     * 
     * @param s Objeto Socio para filtrar las reservas de un cliente específico (o null).
     * @param fecha Fecha de la reserva para filtrar (o null).
     */
    private void cargarTablaReservas(Socio s, LocalDate fecha) {
        
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTableReservas.getModel();
        modeloTabla.setRowCount(0);

        ArrayList<Reserva> lista = Gimnasio.getInstancia().buscarReservas(s, fecha); 

        for (Reserva res : lista) {

            Object[] fila = new Object[3]; 

            fila[0] = res.getFechaReserva();
            fila[1] = res.getCliente().getCorreo();
            fila[2] = res.getActividad().getTitulo();
            
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ConsultaDeActividades = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMonitor = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonLimpiarActividades = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();
        ConsultaDeReservas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jSpinnerFecha = new javax.swing.JSpinner();
        GestiónDeActividades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonGuardarActividad = new javax.swing.JButton();
        jButtonModificarActividad = new javax.swing.JButton();
        jButtonBorrarActividad = new javax.swing.JButton();
        campoTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        campoSala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoAforo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campoMonitor = new javax.swing.JTextField();
        checkBoxEspecial = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonImportarImagen = new javax.swing.JButton();
        jButtonAñadirHorario = new javax.swing.JButton();
        jButtonBorrarHorario = new javax.swing.JButton();
        ConsultaDeSocios = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        checkBoxVip = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jButtonLimpiarSocios = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit");

        jLabel7.setText("Buscar por Tipo:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Musculación", "Cardio", "Natación", "Todos" }));

        jLabel8.setText("Monitor:");

        jTextFieldMonitor.addActionListener(this::jTextFieldMonitorActionPerformed);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        jButtonLimpiarActividades.setText("Limpiar");
        jButtonLimpiarActividades.addActionListener(this::jButtonLimpiarActividadesActionPerformed);

        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Tipo", "Monitor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableActividadesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableActividades);

        javax.swing.GroupLayout ConsultaDeActividadesLayout = new javax.swing.GroupLayout(ConsultaDeActividades);
        ConsultaDeActividades.setLayout(ConsultaDeActividadesLayout);
        ConsultaDeActividadesLayout.setHorizontalGroup(
            ConsultaDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpiarActividades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        ConsultaDeActividadesLayout.setVerticalGroup(
            ConsultaDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonLimpiarActividades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Actividades", ConsultaDeActividades);

        jLabel11.setText("Consultar desde la fecha:");

        jButton8.setText("Buscar");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton9.setText("Ver todas");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Socio", "Actividad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReservasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableReservas);
        if (jTableReservas.getColumnModel().getColumnCount() > 0) {
            jTableReservas.getColumnModel().getColumn(1).setResizable(false);
        }

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFecha.setToolTipText("");
        jSpinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy"));

        javax.swing.GroupLayout ConsultaDeReservasLayout = new javax.swing.GroupLayout(ConsultaDeReservas);
        ConsultaDeReservas.setLayout(ConsultaDeReservasLayout);
        ConsultaDeReservasLayout.setHorizontalGroup(
            ConsultaDeReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(20, 20, 20))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        ConsultaDeReservasLayout.setVerticalGroup(
            ConsultaDeReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Reservas", ConsultaDeReservas);

        jLabel1.setText("Título");

        jButtonGuardarActividad.setText("Guardar");
        jButtonGuardarActividad.addActionListener(this::jButtonGuardarActividadActionPerformed);

        jButtonModificarActividad.setText("Modificar");
        jButtonModificarActividad.addActionListener(this::jButtonModificarActividadActionPerformed);

        jButtonBorrarActividad.setText("Eliminar");
        jButtonBorrarActividad.addActionListener(this::jButtonBorrarActividadActionPerformed);

        campoTitulo.addActionListener(this::campoTituloActionPerformed);

        jLabel2.setText("Tipo de Actividad");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Musculación", "Cardio", "Natación" }));

        jLabel3.setText("Sala");

        jLabel4.setText("Aforo");

        jLabel5.setText("Horarios");

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00 a 11:00", "11:00 a 12:00", "18:00 a 19:00", "19:00 a 20:00", "20:00 a 21:00" }));

        jLabel6.setText("Monitor");

        checkBoxEspecial.setText("¿Es actividad especial?");

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        jLabel13.setText("Precio");

        jLabel14.setText("Descripción:");

        jButtonImportarImagen.setText("Importar imágen");
        jButtonImportarImagen.addActionListener(this::jButtonImportarImagenActionPerformed);

        jButtonAñadirHorario.setText("Añadir horario");
        jButtonAñadirHorario.addActionListener(this::jButtonAñadirHorarioActionPerformed);

        jButtonBorrarHorario.setText("Borrar horario");
        jButtonBorrarHorario.addActionListener(this::jButtonBorrarHorarioActionPerformed);

        javax.swing.GroupLayout GestiónDeActividadesLayout = new javax.swing.GroupLayout(GestiónDeActividades);
        GestiónDeActividades.setLayout(GestiónDeActividadesLayout);
        GestiónDeActividadesLayout.setHorizontalGroup(
            GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jButtonGuardarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(jButtonModificarActividad)
                        .addGap(101, 101, 101)
                        .addComponent(jButtonBorrarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(checkBoxEspecial)
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonAñadirHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarHorario))
                    .addGroup(GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestiónDeActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestiónDeActividadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonImportarImagen)
                .addGap(189, 189, 189))
        );
        GestiónDeActividadesLayout.setVerticalGroup(
            GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestiónDeActividadesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAñadirHorario)
                        .addComponent(jButtonBorrarHorario))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImportarImagen)
                .addGap(9, 9, 9)
                .addComponent(checkBoxEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(GestiónDeActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarActividad)
                    .addComponent(jButtonModificarActividad)
                    .addComponent(jButtonBorrarActividad))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Gestión de Actividades", GestiónDeActividades);

        jLabel10.setText("Buscar por correo electrónico:");

        checkBoxVip.setText("Socios VIP");

        jButton6.setText("Buscar");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButtonLimpiarSocios.setText("Limpiar");
        jButtonLimpiarSocios.addActionListener(this::jButtonLimpiarSociosActionPerformed);

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "¿Es VIP?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSociosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSocios);

        javax.swing.GroupLayout ConsultaDeSociosLayout = new javax.swing.GroupLayout(ConsultaDeSocios);
        ConsultaDeSocios.setLayout(ConsultaDeSociosLayout);
        ConsultaDeSociosLayout.setHorizontalGroup(
            ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxVip)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(83, 83, 83)
                        .addComponent(jButtonLimpiarSocios)
                        .addGap(142, 142, 142))))
        );
        ConsultaDeSociosLayout.setVerticalGroup(
            ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeSociosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxVip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaDeSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLimpiarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );

        jTabbedPane1.addTab("Consulta de Socios", ConsultaDeSocios);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("JavaFit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Maneja el evento del botón para modificar una actividad existente.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonModificarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActividadActionPerformed
        // TODO add your handling code here:
        String titulo = campoTitulo.getText().trim();
        
        if (titulo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo 'Título' no puede estar vacío.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Actividad> listaActividades = Gimnasio.getInstancia().getActividades();
        
        Actividad act = listaActividades.stream()
                .filter(a -> a.getTitulo().equalsIgnoreCase(titulo))
                .findFirst()
                .orElse(null);

        if (act == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna actividad con el título '" + titulo + "'.", "Actividad no encontrada", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nuevoTipo = comboTipo.getSelectedItem().toString();
        String nuevoMonitor = campoMonitor.getText().trim();
        String nombreSala = campoSala.getText().trim();

        if (nuevoMonitor.isEmpty() || nombreSala.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monitor y la sala no pueden quedar vacíos.");
            return;
        }
        
        // Se comprueba que el aforo sea un número
        try {
            int nuevoAforo = Integer.parseInt(campoAforo.getText().trim());
            Sala nuevaSala = new Sala(nombreSala, nuevoAforo);

            double nuevoPrecio = 0;
            String nuevaDescripcion = "";

            if (checkBoxEspecial.isSelected()) {
                nuevoPrecio = Double.parseDouble(campoPrecio.getText().trim());
                nuevaDescripcion = campoDescripcion.getText().trim();
            }

            boolean modificacionRealizada = Gimnasio.getInstancia().modificarActividad(act, titulo, nuevoTipo, nuevaSala, nuevoMonitor, this.imagenActividad, nuevoPrecio, nuevaDescripcion);

            if (modificacionRealizada) {
                javax.swing.JOptionPane.showMessageDialog(this, "Actividad '" + titulo + "' modificada con éxito");
                
                // Se limpian los campos de texto
                
                campoTitulo.setText("");
                campoMonitor.setText("");
                campoSala.setText("");
                campoAforo.setText("");
                campoPrecio.setText("");
                campoDescripcion.setText("");
                checkBoxEspecial.setSelected(false);
                this.imagenActividad = null;
                
            } 
            else {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al intentar modificar.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "'Aforo' y 'Precio' deben ser números.", "Error de datos", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActividadActionPerformed
    /**
     * Maneja el evento del botón para guardar una nueva actividad.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonGuardarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActividadActionPerformed
        // TODO add your handling code here:
        String titulo = campoTitulo.getText().trim();
        String tipo = comboTipo.getSelectedItem().toString(); 
        String monitor = campoMonitor.getText().trim();
        String nombreSala = campoSala.getText().trim();

        if (titulo.isEmpty() || monitor.isEmpty() || nombreSala.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El título, monitor y sala son obligatorios.");
            return;
        }
    
        if (horarios.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, 
                        "Se debe añadir al menos un horario utilizando el botón 'Añadir horario'.",
                        "Faltan horarios",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
        }


        try {

            int aforo = Integer.parseInt(campoAforo.getText().trim());
            Sala sala = new Sala(nombreSala, aforo);

            boolean creacionActividad = false;

            if (checkBoxEspecial.isSelected()) { 
                double precio = Double.parseDouble(campoPrecio.getText().trim());
                String descripcion = campoDescripcion.getText().trim();

                creacionActividad = Gimnasio.getInstancia().crearActividad(titulo, tipo, sala, new java.util.ArrayList<>(this.horarios), monitor, this.imagenActividad, precio, descripcion);
            } 
            else {
                creacionActividad = Gimnasio.getInstancia().crearActividad(titulo, tipo, sala, new java.util.ArrayList<>(this.horarios), monitor, this.imagenActividad);
            }

            if (creacionActividad) {
                javax.swing.JOptionPane.showMessageDialog(this, "Actividad '" + titulo + "' creada con éxito");
                this.horarios.clear();
            } 
            else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Ya existe una actividad con ese título.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "'Aforo' y 'Precio' deben ser números.", "Error de datos", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_jButtonGuardarActividadActionPerformed
    /**
     * Maneja el evento del botón para buscar actividades según los filtros especificados.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String tipoBuscado = jComboBoxTipo.getSelectedItem().toString();
        String monitorBuscado = jTextFieldMonitor.getText().trim();
        String dia = null;

        if (tipoBuscado.equals("Todos")) {
            tipoBuscado = null;
        }

        if (monitorBuscado.isEmpty()) {
            monitorBuscado = null;
        }
        
        cargarTablaActividades(tipoBuscado, monitorBuscado, dia);

    }//GEN-LAST:event_jButtonBuscarActionPerformed
    /**
     * Maneja el evento del botón para limpiar los filtros de búsqueda de actividades.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonLimpiarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActividadesActionPerformed
        // TODO add your handling code here:
        jTextFieldMonitor.setText("");
        jComboBoxTipo.setSelectedItem("Todos");
    }//GEN-LAST:event_jButtonLimpiarActividadesActionPerformed
    /**
     * Maneja el evento del botón para buscar socios según los filtros especificados.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            String correo = jTextFieldCorreo.getText().trim();
            if (correo.isEmpty()) 
                correo = null; // Si está vacío, mandamos null

            // Comprobamos si marcó la casilla de VIP
            Boolean esVip = checkBoxVip.isSelected();
            if (!esVip) 
                esVip = null; // Si no la marcó, mandamos null para que no filtre por VIP

            // Recargamos la tabla con esos filtros
            cargarTablaSocios(correo, esVip);
    }//GEN-LAST:event_jButton6ActionPerformed
    /**
     * Maneja el evento del botón para limpiar los filtros de búsqueda de socios.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonLimpiarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarSociosActionPerformed
        // TODO add your handling code here:
        jTextFieldCorreo.setText("");
        checkBoxVip.setSelected(false);
        cargarTablaSocios(null, null);
    }//GEN-LAST:event_jButtonLimpiarSociosActionPerformed
    /**
     * Maneja el evento del botón para buscar reservas según la fecha especificada.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        // 1. Obtenemos la fecha del JSpinner
        java.util.Date fechaSpinner = (java.util.Date) jSpinnerFecha.getValue();

        // 2. Pasamos de Date a LocalDate usando GregorianCalendar
        java.util.GregorianCalendar cal = new java.util.GregorianCalendar();
        cal.setTime(fechaSpinner);

        LocalDate fecha = LocalDate.of(
            cal.get(java.util.Calendar.YEAR),
            cal.get(java.util.Calendar.MONTH) + 1, // Se le suma 1 porque en Calendar los meses van de 0 a 11
            cal.get(java.util.Calendar.DAY_OF_MONTH)
        );

        // 3. Limpiamos la tabla de reservas
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableReservas.getModel();
        modelo.setRowCount(0);

        // 4. Buscamos en el gimnasio (null por administrador)
        java.util.ArrayList<Reserva> reservasFiltradas = Gimnasio.getInstancia().buscarReservas(null, fecha);

        // 5. Pintamos los resultados en la tabla
        for (Reserva res : reservasFiltradas) {
            Object[] fila = new Object[3];
            fila[0] = res.getFechaReserva();             
            fila[1] = res.getCliente().getCorreo();        
            fila[2] = res.getActividad().getTitulo();    
            modelo.addRow(fila);
    }
    
    }//GEN-LAST:event_jButton8ActionPerformed
    /**
     * Maneja el evento del botón para importar una imagen para una actividad.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonImportarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarImagenActionPerformed
        // TODO add your handling code here:
        
    javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
    
    javax.swing.filechooser.FileNameExtensionFilter filtro = 
            new javax.swing.filechooser.FileNameExtensionFilter("Imágenes (JPG, PNG)", "jpg", "jpeg", "png");
    selector.setFileFilter(filtro);
    
    int resultado = selector.showOpenDialog(this);
    
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivoImagen = selector.getSelectedFile();
        
        this.imagenActividad = new ImageIcon(archivoImagen.getAbsolutePath());
        
        }
    }//GEN-LAST:event_jButtonImportarImagenActionPerformed
    /**
     * Maneja el evento del botón para eliminar una actividad existente.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonBorrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActividadActionPerformed
        // TODO add your handling code here:
            String titulo= campoTitulo.getText().trim();
            
            if (titulo.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El campo 'Título' no puede estar vacío.","Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
            boolean eliminado= Gimnasio.getInstancia().borrarActividad(titulo);
            
            if (eliminado==true){
                javax.swing.JOptionPane.showMessageDialog(this, "Actividad eliminada correctamente.");
                
                campoTitulo.setText("");
                campoMonitor.setText("");
                campoSala.setText("");
                campoAforo.setText("");
                campoPrecio.setText("");
                campoDescripcion.setText("");
                this.imagenActividad = null;
            }
            else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna actividad con ese título.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_jButtonBorrarActividadActionPerformed
    /**
     * Maneja el evento de acción del campo de texto del título.
     * 
     * @param evt Evento de acción disparado por el campo de texto.
     */
    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed
    /**
     * Maneja el evento de clic del ratón sobre la tabla de actividades para mostrar sus detalles.
     * 
     * @param evt Evento de ratón disparado por la tabla.
     */
    private void jTableActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableActividadesMouseClicked
        // TODO add your handling code here:
        int fila= jTableActividades.getSelectedRow();
        
        if (fila>=0){
            
            String titulo= jTableActividades.getValueAt(fila,0).toString();
            
            Actividad actSeleccionada= Gimnasio.getInstancia().getActividades().stream()
                    .filter(a -> a.getTitulo().equalsIgnoreCase(titulo))
                    .findFirst()
                    .orElse(null);
            
            if (actSeleccionada!=null)
                if(actSeleccionada instanceof ActividadEspecial){
                    
                    VentanaActividadEspecial ficha = new VentanaActividadEspecial((ActividadEspecial) actSeleccionada);
                    ficha.setVisible(true);
                    ficha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            
                }
                else{
                    
                    VentanaActividad ficha = new VentanaActividad(actSeleccionada);
                    ficha.setVisible(true);
                    ficha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                }
            }
    }//GEN-LAST:event_jTableActividadesMouseClicked
    /**
     * Maneja el evento de acción del campo de texto del monitor.
     * 
     * @param evt Evento de acción disparado por el campo de texto.
     */
    private void jTextFieldMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorActionPerformed
    /**
     * Maneja el evento del botón para añadir un nuevo horario a la actividad en creación o modificación.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonAñadirHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirHorarioActionPerformed
        // TODO add your handling code here:
        String dia = jComboBoxDia.getSelectedItem().toString();
        String turno = jComboBoxTurno.getSelectedItem().toString();
        
        Horario nuevoHorario = new Horario(dia, turno);
        
        for (Horario h : horarios) {
            if (h.getDia().equalsIgnoreCase(dia) && h.getTurno().equalsIgnoreCase(turno)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Este horario (" + dia + " - " + turno + ") ya ha sido añadido a la lista actual.",
                        "Horario duplicado", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return; 
            }
        }
        
        horarios.add(nuevoHorario);
        
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Horario guardado: " + dia + " de " + turno + ".\nTotal de turnos acumulados: " + horarios.size());
        
    }//GEN-LAST:event_jButtonAñadirHorarioActionPerformed
    /**
     * Maneja el evento del botón para borrar un horario de la actividad en creación o modificación.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButtonBorrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarHorarioActionPerformed
        // TODO add your handling code here:
        String dia = jComboBoxDia.getSelectedItem().toString();
        String turno = jComboBoxTurno.getSelectedItem().toString();
        
        boolean exito= false;
        
        for (int i= 0; i<horarios.size();i++) {
            Horario h = horarios.get(i);
            if (h.getDia().equalsIgnoreCase(dia) && h.getTurno().equalsIgnoreCase(turno)) {
            horarios.remove(h);
            exito= true;
            }
        }
        
        if(exito){
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "El horario (" + dia + " - " + turno + ") ha sido eliminado.",
                    "Horario eliminado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Ese horario no se encontraba en la lista provisional actual.",
                    "Horario no encontrado", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonBorrarHorarioActionPerformed
    /**
     * Maneja el evento del botón para ver todas las reservas sin filtrar.
     * 
     * @param evt Evento de acción disparado por el botón.
     */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
    /**
     * Maneja el evento de clic del ratón sobre la tabla de socios para mostrar su ficha.
     * 
     * @param evt Evento de ratón disparado por la tabla.
     */
    private void jTableSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSociosMouseClicked
        // TODO add your handling code here:
        int fila = jTableSocios.getSelectedRow();

        if (fila >= 0) {

            String correoSocio = jTableSocios.getValueAt(fila, 1).toString();

            Socio socioSeleccionado = Gimnasio.getInstancia().getSocios().stream()
                    .filter(s -> s.getCorreo().equalsIgnoreCase(correoSocio)) 
                    .findFirst()
                    .orElse(null);

            if (socioSeleccionado != null) {
                VentanaSocio ficha = new VentanaSocio(socioSeleccionado);
                ficha.setVisible(true);
                ficha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            }
        }
    }//GEN-LAST:event_jTableSociosMouseClicked
    /**
     * Maneja el evento de clic del ratón sobre la tabla de reservas para mostrar su detalle.
     * 
     * @param evt Evento de ratón disparado por la tabla.
     */
    private void jTableReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReservasMouseClicked
        // TODO add your handling code here:
        int fila= jTableReservas.getSelectedRow();
        
        if (fila>=0){
            
            String correoCliente = jTableReservas.getValueAt(fila, 1).toString();
            String tituloActividad = jTableReservas.getValueAt(fila, 2).toString();


            Reserva reservaEncontrada = Gimnasio.getInstancia().getReservas().stream()
                    .filter(r -> r.getCliente().getCorreo().equalsIgnoreCase(correoCliente) && r.getActividad().getTitulo().equalsIgnoreCase(tituloActividad))
                    .findFirst()
                    .orElse(null);

            if (reservaEncontrada != null) {
                            VentanaReserva ficha = new VentanaReserva(reservaEncontrada);
                            ficha.setVisible(true);
                            ficha.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            }
        }
    }//GEN-LAST:event_jTableReservasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaGestionAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConsultaDeActividades;
    private javax.swing.JPanel ConsultaDeReservas;
    private javax.swing.JPanel ConsultaDeSocios;
    private javax.swing.JPanel GestiónDeActividades;
    private javax.swing.JTextField campoAforo;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoMonitor;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoSala;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JCheckBox checkBoxEspecial;
    private javax.swing.JCheckBox checkBoxVip;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAñadirHorario;
    private javax.swing.JButton jButtonBorrarActividad;
    private javax.swing.JButton jButtonBorrarHorario;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGuardarActividad;
    private javax.swing.JButton jButtonImportarImagen;
    private javax.swing.JButton jButtonLimpiarActividades;
    private javax.swing.JButton jButtonLimpiarSocios;
    private javax.swing.JButton jButtonModificarActividad;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableActividades;
    private javax.swing.JTable jTableReservas;
    private javax.swing.JTable jTableSocios;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldMonitor;
    // End of variables declaration//GEN-END:variables
    private javax.swing.ImageIcon imagenActividad = null;
    private ArrayList<Horario> horarios = new ArrayList<>();
}

